package org.hagelbrand.service.spotify;

import org.hagelbrand.data.CreatePlaylistRequest;
import org.springframework.http.HttpHeaders;
import org.springframework.security.oauth2.client.OAuth2AuthorizedClient;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;
import org.springframework.web.reactive.function.client.WebClient;

import java.util.List;
import java.util.Map;
import java.util.Objects;

@Service
public class SpotifyPlaylistService {

    private final WebClient spotifyClient;

    public SpotifyPlaylistService(WebClient spotifyWebClient) {
        this.spotifyClient = spotifyWebClient;
    }

    public String createPlaylist(
            OAuth2AuthorizedClient client,
            String userId,
            String artist
    ) {
        return spotifyClient.post()
                .uri("/users/{userId}/playlists", userId)
                .headers(h ->
                        h.setBearerAuth(client.getAccessToken().getTokenValue()))
                .bodyValue(new CreatePlaylistRequest(
                        artist + " – Predicted Setlist",
                        "Generated by HagelBrand using setlist.fm data",
                        false
                ))
                .retrieve()
                .bodyToMono(Map.class)
                .map(m -> m.get("id").toString())
                .block();
    }

    public void addTracks(
            OAuth2AuthorizedClient client,
            String playlistId,
            List<String> trackIds
    ) {
        List<String> uris = trackIds.stream()
                .map(id -> "spotify:track:" + id)
                .toList();

        spotifyClient.post()
                .uri("/playlists/{playlistId}/tracks", playlistId)
                .headers(h ->
                        h.setBearerAuth(client.getAccessToken().getTokenValue()))
                .bodyValue(Map.of("uris", uris))
                .retrieve()
                .bodyToMono(Void.class)
                .block();
    }
}

